version: '3'
services:
  web:
    build: .
    container_name: choose_template
    external_links:
      - mongo:mongo
    volumes:
      - ./app:/app
    ports:
      - "80:80"
  mongodb:
    image: mongo:latest
    container_name: mongo
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"